#!/usr/bin/env bash
# Registers the JobFill native messaging host for Chrome on macOS.
# Usage: ./install.sh <EXTENSION_ID>
# Find the extension id at chrome://extensions (enable Developer mode, load
# tools/jobfill/extension as an unpacked extension, copy its ID).
set -euo pipefail

EXT_ID="${1:?Pass the unpacked extension ID: ./install.sh <EXTENSION_ID>}"
DIR="$(cd "$(dirname "$0")" && pwd)"
HOST_NAME="com.akash.jobfill"

# A tiny launcher so Chrome gets an absolute, env-stable entrypoint.
# Chrome's PATH is minimal, so we bake in absolute node/claude/codex paths.
NODE_BIN="$(command -v node || true)"
CLAUDE_BIN="$(command -v claude || true)"
CODEX_BIN="$(command -v codex || true)"
[ -z "$NODE_BIN" ] && { echo "ERROR: node not found on PATH"; exit 1; }
[ -z "$CLAUDE_BIN" ] && echo "WARNING: 'claude' not found on PATH — Generate all will fail until it's installed."

LAUNCHER="$DIR/jobfill-host-launcher.sh"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by install.sh — gives Chrome's minimal env the right binaries.
export PATH="$(dirname "$NODE_BIN"):${CLAUDE_BIN:+$(dirname "$CLAUDE_BIN"):}/opt/homebrew/bin:/usr/local/bin:\$HOME/.local/bin:\$PATH"
export JOBFILL_CLAUDE_BIN="${CLAUDE_BIN:-claude}"
export JOBFILL_CODEX_BIN="${CODEX_BIN:-codex}"
exec "$NODE_BIN" "$DIR/jobfill-host.mjs"
EOF
chmod +x "$LAUNCHER" "$DIR/jobfill-host.mjs"
echo "node=$NODE_BIN  claude=${CLAUDE_BIN:-MISSING}  codex=${CODEX_BIN:-MISSING}"

# Chrome host manifest location on macOS:
TARGET_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
mkdir -p "$TARGET_DIR"
sed -e "s#REPLACE_WITH_ABSOLUTE_PATH/jobfill-host-launcher.sh#$LAUNCHER#" \
    -e "s#REPLACE_WITH_EXTENSION_ID#$EXT_ID#" \
    "$DIR/com.akash.jobfill.template.json" > "$TARGET_DIR/$HOST_NAME.json"

echo "Installed host manifest -> $TARGET_DIR/$HOST_NAME.json"
echo "Launcher -> $LAUNCHER"
echo "Restart Chrome, then use the side panel. (Linux path: ~/.config/google-chrome/NativeMessagingHosts/)"
